@echo off
setlocal enabledelayedexpansion
REM Auto-generated by deploy-package.sh
set SCRIPT_DIR=%~dp0
set BACKEND_DIR=%SCRIPT_DIR%backend
set JAR_NAME=backend-0.0.1-SNAPSHOT.jar
set SPRING_PROFILES_ACTIVE=postgres
if "%JAVA_OPTS%"=="" set JAVA_OPTS=-Xms512m -Xmx1024m
if not exist "%BACKEND_DIR%\%JAR_NAME%" (
  echo [ERROR] %JAR_NAME% not found in %BACKEND_DIR%
  exit /b 1
)
if "%LOG_DIR%"=="" set LOG_DIR=%SCRIPT_DIR%logs
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
echo Starting backend with profile=%SPRING_PROFILES_ACTIVE% ...
pushd "%BACKEND_DIR%" >nul
java %JAVA_OPTS% -Dspring.profiles.active=%SPRING_PROFILES_ACTIVE% -jar "%JAR_NAME%" 1>>"%LOG_DIR%\stdout.log" 2>>"%LOG_DIR%\stderr.log"
popd >nul
endlocal
