@echo off
setlocal enabledelayedexpansion

REM TNT Sales — Build and Package (Windows)
REM - Builds PC and Mobile frontends, backend JAR
REM - Packages into tnt_sales_dlv for deployment

REM Resolve repo root (this script lives in tnt_sales/scripts)
set SCRIPT_DIR=%~dp0
for %%I in ("%SCRIPT_DIR%..") do set ROOT=%%~fI

set FRONT_PC=%ROOT%\frontend
set FRONT_MB=%ROOT%\frontend_mb
set BACKEND=%ROOT%\backend
set DLV=%ROOT%\tnt_sales_dlv

echo [1/6] Ensuring output directories...
mkdir "%DLV%" 2>nul
mkdir "%DLV%\frontend" 2>nul
mkdir "%DLV%\frontend\sales" 2>nul
mkdir "%DLV%\frontend\sales\mobile" 2>nul
mkdir "%DLV%\backend" 2>nul

REM Helper: run NPM CI or fallback to install
set CMD_NPM_CI=npm ci
set CMD_VITE_BUILD=npx vite build

echo.
echo [2/6] Building PC frontend (vite build)...
pushd "%FRONT_PC%"
if exist package-lock.json (
  %CMD_NPM_CI%
) else (
  npm install
)
%CMD_VITE_BUILD%
if errorlevel 1 (
  echo [ERROR] PC frontend build failed.
  popd
  exit /b 1
)
popd

echo.
echo [3/6] Building Mobile frontend (vite build)...
pushd "%FRONT_MB%"
if exist package-lock.json (
  %CMD_NPM_CI%
) else (
  npm install
)
%CMD_VITE_BUILD%
if errorlevel 1 (
  echo [ERROR] Mobile frontend build failed.
  popd
  exit /b 1
)
popd

echo.
echo [4/6] Building backend (Maven package -DskipTests)...
pushd "%BACKEND%"
mvn -q clean package -DskipTests
if errorlevel 1 (
  echo [ERROR] Backend build failed.
  popd
  exit /b 1
)
popd

echo.
echo [5/6] Copying artifacts into tnt_sales_dlv ...
REM PC frontend
if exist "%DLV%\frontend\sales\*" rmdir /s /q "%DLV%\frontend\sales" 2>nul
mkdir "%DLV%\frontend\sales" 2>nul
xcopy /e /i /y "%FRONT_PC%\dist\*" "%DLV%\frontend\sales\" >nul

REM Mobile frontend
if exist "%DLV%\frontend\sales\mobile\*" rmdir /s /q "%DLV%\frontend\sales\mobile" 2>nul
mkdir "%DLV%\frontend\sales\mobile" 2>nul
xcopy /e /i /y "%FRONT_MB%\dist\*" "%DLV%\frontend\sales\mobile\" >nul

REM Backend JAR and configs
copy /y "%BACKEND%\target\backend-0.0.1-SNAPSHOT.jar" "%DLV%\backend\backend-0.0.1-SNAPSHOT.jar" >nul
copy /y "%BACKEND%\src\main\resources\application.yml" "%DLV%\backend\application.yml" >nul
copy /y "%BACKEND%\src\main\resources\application-postgres.yml" "%DLV%\backend\application-postgres.yml" >nul
copy /y "%BACKEND%\src\main\resources\application-prod.yml" "%DLV%\backend\application-prod.yml" >nul
copy /y "%BACKEND%\src\main\resources\activity-ai-tables.yml" "%DLV%\backend\activity-ai-tables.yml" >nul
copy /y "%BACKEND%\src\main\resources\sales-ai-tables.yml" "%DLV%\backend\sales-ai-tables.yml" >nul

echo.
echo [5.5/6] Generating backend launchers (BAT/SH)...
(
  echo @echo off
  echo setlocal enabledelayedexpansion
  echo REM Auto-generated by deploy-package.bat
  echo set SCRIPT_DIR=%%~dp0
  echo set BACKEND_DIR=%%SCRIPT_DIR%%backend
  echo set JAR_NAME=backend-0.0.1-SNAPSHOT.jar
  echo set SPRING_PROFILES_ACTIVE=prod,postgres
  echo if "%%JAVA_OPTS%%"=="" set JAVA_OPTS=-Xms512m -Xmx1024m
  echo if not exist "%%BACKEND_DIR%%\%%JAR_NAME%%" ^(
  echo ^  echo [ERROR] %%JAR_NAME%% not found in %%BACKEND_DIR%%
  echo ^  exit /b 1
  echo ^)
  echo if "%%LOG_DIR%%"=="" set LOG_DIR=%%SCRIPT_DIR%%logs
  echo if not exist "%%LOG_DIR%%" mkdir "%%LOG_DIR%%"
  echo echo Starting backend with profile=%%SPRING_PROFILES_ACTIVE%% ...
  echo pushd "%%BACKEND_DIR%%" ^>nul
  echo java %%JAVA_OPTS%% -Dspring.profiles.active=%%SPRING_PROFILES_ACTIVE%% -jar "%%JAR_NAME%%" 1^>^>"%%LOG_DIR%%\stdout.log" 2^>^>"%%LOG_DIR%%\stderr.log"
  echo popd ^>nul
  echo endlocal
) > "%DLV%\run-backend.bat"

REM Also create a POSIX launcher for *nix hosts
(
  echo #!/usr/bin/env bash
  echo set -euo pipefail
  echo SCRIPT_DIR="\$\(cd \"\$\(dirname \"\${BASH_SOURCE[0]}\"\)\" && pwd\)"
  echo BACKEND_DIR="\${SCRIPT_DIR}/backend"
  echo JAR_NAME="backend-0.0.1-SNAPSHOT.jar"
  echo SPRING_PROFILES_ACTIVE="\${SPRING_PROFILES_ACTIVE:-prod,postgres}"
  echo JAVA_OPTS="\${JAVA_OPTS:--Xms512m -Xmx1024m}"
  echo LOG_DIR="\${LOG_DIR:-\${SCRIPT_DIR}/logs}"
  echo mkdir -p "\${LOG_DIR}"
  echo 'if [[ ! -f "${BACKEND_DIR}/${JAR_NAME}" ]]; then'
  echo '  echo "[ERROR] ${JAR_NAME} not found in ${BACKEND_DIR}" >&2'
  echo '  exit 1'
  echo fi
  echo echo "Starting backend with profile=\${SPRING_PROFILES_ACTIVE} ..."
  echo cd "\${BACKEND_DIR}"
  echo exec java \${JAVA_OPTS} -Dspring.profiles.active="\${SPRING_PROFILES_ACTIVE}" -jar "\${JAR_NAME}" ^>^>"\${LOG_DIR}/stdout.log" 2^>^>"\${LOG_DIR}/stderr.log"
) > "%DLV%\run-backend.sh"
REM Best-effort: mark executable if running on Git Bash or similar
where bash >nul 2>&1 && bash -lc "chmod +x \"$(cygpath -u '%DLV%')/run-backend.sh\"" 2>nul

echo.
echo [6/6] Verifying package contents...
dir /b "%DLV%\frontend\sales"
echo --- mobile
dir /b "%DLV%\frontend\sales\mobile"
echo --- backend
dir /b "%DLV%\backend"
echo --- launchers
dir /b "%DLV%" | findstr /i "run-backend.bat" >nul && echo run-backend.bat
dir /b "%DLV%" | findstr /i "run-backend.sh" >nul && echo run-backend.sh

REM Optional: print SHA256 checksums if certutil is available
where certutil >nul 2>&1
if not errorlevel 1 (
  echo --- checksums
  certutil -hashfile "%DLV%\backend\backend-0.0.1-SNAPSHOT.jar" SHA256 | find /i "SHA256" >nul
  certutil -hashfile "%DLV%\backend\backend-0.0.1-SNAPSHOT.jar" SHA256
)

echo.
echo Done. Copy the folder '%DLV%' to deploy.
endlocal
