#!/usr/bin/env bash
set -euo pipefail

# TNT Sales — Build and Package (POSIX)
# - Builds PC and Mobile frontends, backend JAR
# - Packages into tnt_sales_dlv for deployment

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="${SCRIPT_DIR%/scripts}"

FRONT_PC="${ROOT}/frontend"
FRONT_MB="${ROOT}/frontend_mb"
BACKEND="${ROOT}/backend"
DLV="${ROOT}/tnt_sales_dlv"

step() { echo; echo "[$1] $2"; }

step 1 "Ensuring output directories..."
mkdir -p "${DLV}/frontend/sales/mobile" "${DLV}/backend"

build_frontend() {
  local dir="$1"; local name="$2"
  step "build-${name}" "Building ${name} frontend (vite build)..."
  pushd "$dir" >/dev/null
  if [[ -f package-lock.json ]]; then
    npm ci
  else
    npm install
  fi
  npx vite build
  popd >/dev/null
}

step 2 "Building PC frontend"
build_frontend "${FRONT_PC}" "pc"

step 3 "Building Mobile frontend"
build_frontend "${FRONT_MB}" "mobile"

step 4 "Building backend (Maven package -DskipTests)"
pushd "${BACKEND}" >/dev/null
mvn -q clean package -DskipTests
popd >/dev/null

step 5 "Copying artifacts into tnt_sales_dlv"
rm -rf "${DLV}/frontend/sales"
mkdir -p "${DLV}/frontend/sales" "${DLV}/frontend/sales/mobile"
cp -r "${FRONT_PC}/dist/"* "${DLV}/frontend/sales/"
rm -rf "${DLV}/frontend/sales/mobile"
mkdir -p "${DLV}/frontend/sales/mobile"
cp -r "${FRONT_MB}/dist/"* "${DLV}/frontend/sales/mobile/"
cp -f "${BACKEND}/target/backend-0.0.1-SNAPSHOT.jar" "${DLV}/backend/backend-0.0.1-SNAPSHOT.jar"
cp -f "${BACKEND}/src/main/resources/application.yml" "${DLV}/backend/application.yml"
cp -f "${BACKEND}/src/main/resources/application-postgres.yml" "${DLV}/backend/application-postgres.yml"
cp -f "${BACKEND}/src/main/resources/application-prod.yml" "${DLV}/backend/application-prod.yml"
cp -f "${BACKEND}/src/main/resources/activity-ai-tables.yml" "${DLV}/backend/activity-ai-tables.yml"
cp -f "${BACKEND}/src/main/resources/sales-ai-tables.yml" "${DLV}/backend/sales-ai-tables.yml"

# 5.5 Generate backend launcher (run-backend.sh)
step "5.5" "Generating backend launchers (SH/BAT)"
cat > "${DLV}/run-backend.sh" <<'EOS'
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="${SCRIPT_DIR}/backend"
JAR_NAME="backend-0.0.1-SNAPSHOT.jar"
SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE:-postgres,prod}"
JAVA_OPTS="${JAVA_OPTS:--Xms512m -Xmx1024m}"
LOG_DIR="${LOG_DIR:-${SCRIPT_DIR}/logs}"

mkdir -p "${LOG_DIR}"
if [[ ! -f "${BACKEND_DIR}/${JAR_NAME}" ]]; then
  echo "[ERROR] ${JAR_NAME} not found in ${BACKEND_DIR}" >&2
  exit 1
fi

echo "Starting backend with profile=${SPRING_PROFILES_ACTIVE} ..."
cd "${BACKEND_DIR}"
exec java ${JAVA_OPTS} -Dspring.profiles.active="${SPRING_PROFILES_ACTIVE}" -jar "${JAR_NAME}" \
  >>"${LOG_DIR}/stdout.log" 2>>"${LOG_DIR}/stderr.log"
EOS
chmod +x "${DLV}/run-backend.sh"

# Windows BAT launcher as well (for mixed environments)
cat > "${DLV}/run-backend.bat" <<'EOB'
@echo off
setlocal enabledelayedexpansion
REM Auto-generated by deploy-package.sh
set SCRIPT_DIR=%~dp0
set BACKEND_DIR=%SCRIPT_DIR%backend
set JAR_NAME=backend-0.0.1-SNAPSHOT.jar
set SPRING_PROFILES_ACTIVE=postgres,prod
if "%JAVA_OPTS%"=="" set JAVA_OPTS=-Xms512m -Xmx1024m
if not exist "%BACKEND_DIR%\%JAR_NAME%" (
  echo [ERROR] %JAR_NAME% not found in %BACKEND_DIR%
  exit /b 1
)
if "%LOG_DIR%"=="" set LOG_DIR=%SCRIPT_DIR%logs
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
echo Starting backend with profile=%SPRING_PROFILES_ACTIVE% ...
pushd "%BACKEND_DIR%" >nul
java %JAVA_OPTS% -Dspring.profiles.active=%SPRING_PROFILES_ACTIVE% -jar "%JAR_NAME%" 1>>"%LOG_DIR%\stdout.log" 2>>"%LOG_DIR%\stderr.log"
popd >nul
endlocal
EOB

step 6 "Verifying package contents"
ls -la "${DLV}/frontend/sales" | sed -n '1,80p'
echo "--- mobile"
ls -la "${DLV}/frontend/sales/mobile" | sed -n '1,80p'
echo "--- backend"
ls -la "${DLV}/backend" | sed -n '1,80p'
echo "--- launchers"
ls -la "${DLV}/run-backend.sh" 2>/dev/null || true
ls -la "${DLV}/run-backend.bat" 2>/dev/null || true

# Optional: sha256 sums if available
if command -v sha256sum >/dev/null 2>&1; then
  echo "--- checksums"
  sha256sum "${DLV}/backend/backend-0.0.1-SNAPSHOT.jar"
fi

echo
echo "Done. Copy the folder '${DLV}' to deploy."
